<?php

namespace Exod\Bundle\UtopicVillageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HelpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelpRepository extends EntityRepository
{
}