<?php

namespace Exod\Bundle\UtopicVillageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienRepository extends EntityRepository
{
}