<?php

namespace Exod\Bundle\UtopicVillageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function testConnect($email,$password){
		$em = $this->getEntityManager();
		
		//test d'une connection
		$query = $em
			->createQuery('SELECT u FROM ExodUtopicVillageBundle:User u WHERE u.email=:email AND u.password=:password AND u.active=1')
			->setParameter('password',$password)
			->setParameter('email',$email);
		
		if(sizeof($query->getResult())>0){
			return $query->getSingleResult();
		}else{
			return null;
		}
	
		//test de la date de sanction
		//TODO		
	} 
}