<?php

namespace Exod\Bundle\UtopicVillageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VolunteerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolunteerRepository extends EntityRepository
{
	public function deleteAllUserForOneHelp($idHelp){
		$query = $this
			->createQueryBuilder('v')
			->update()
			->set('v.active',0)
			->where('v.help=:idHelp')
			->andWhere('v.active=1')
			->setParameter('idHelp', $idHelp)
			->getQuery();
		$query->execute();
	}
}