<?php

namespace Exod\Bundle\UtopicVillageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VolunteerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolunteerRepository extends EntityRepository
{
}